import { createFileRoute, Link, useParams } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { Download, Printer } from "lucide-react";
import { AppShell } from "@/components/AppShell";
import { StatusPill, VerdictPill } from "@/components/StatusPill";
import { Button } from "@/components/ui/button";
import { getInspection } from "@/lib/store";
import type { Inspection } from "@/lib/types";

export const Route = createFileRoute("/reports/$id")({
  head: () => ({
    meta: [
      { title: "Inspection Report — LabelGuard AI" },
      {
        name: "description",
        content:
          "Digital compliance report for a packaged commodity inspection with extracted declarations, rule references, evidence and officer decisions.",
      },
      { property: "og:title", content: "Inspection Report — LabelGuard AI" },
      {
        property: "og:description",
        content: "Print-ready Legal Metrology compliance report with officer verification record.",
      },
    ],
  }),
  component: ReportPage,
});

function ReportPage() {
  const { id } = useParams({ from: "/reports/$id" });
  const [inspection, setInspection] = useState<Inspection | null>(null);

  useEffect(() => setInspection(getInspection(id) ?? null), [id]);

  if (!inspection) {
    return (
      <AppShell title="Report unavailable" subtitle="Inspection record not found on this device">
        <div className="panel p-8 text-center">
          <Button asChild>
            <Link to="/inspections">Back to inspection history</Link>
          </Button>
        </div>
      </AppShell>
    );
  }

  function exportCsv() {
    const rows = [
      [
        "Requirement",
        "Category",
        "Rule reference",
        "Extracted value",
        "Status",
        "Confidence",
        "Officer decision",
        "Explanation",
      ],
      ...inspection!.checks.map((c) => [
        c.requirement,
        c.category,
        c.ruleReference,
        c.extractedValue ?? "Not detected",
        c.status,
        `${Math.round(c.confidence * 100)}%`,
        c.decision,
        c.explanation,
      ]),
    ];
    const csv = rows
      .map((r) => r.map((cell) => `"${String(cell).replace(/"/g, '""')}"`).join(","))
      .join("\n");
    const url = URL.createObjectURL(new Blob([csv], { type: "text/csv;charset=utf-8" }));
    const a = document.createElement("a");
    a.href = url;
    a.download = `${inspection!.id}-compliance-report.csv`;
    a.click();
    URL.revokeObjectURL(url);
  }

  const violations = inspection.checks.filter((c) => c.status === "FAIL");

  return (
    <AppShell
      title="Inspection report"
      subtitle={`${inspection.id} · ${inspection.productName}`}
      actions={
        <div className="flex gap-2">
          <Button size="sm" variant="outline" onClick={exportCsv}>
            <Download className="mr-1.5 h-4 w-4" />
            Export CSV
          </Button>
          <Button size="sm" onClick={() => window.print()}>
            <Printer className="mr-1.5 h-4 w-4" />
            Download PDF
          </Button>
        </div>
      }
    >
      <article className="panel mx-auto max-w-4xl p-6 sm:p-8">
        <header className="border-b border-border pb-5">
          <p className="label-caps">Department of Consumer Affairs</p>
          <h2 className="mt-1 font-serif text-2xl">
            Packaged Commodity Compliance Inspection Report
          </h2>
          <p className="mt-1 text-xs text-muted-foreground">
            Legal Metrology Act, 2009 · Legal Metrology (Packaged Commodities) Rules, 2011 ·
            Generated by LabelGuard AI
          </p>
        </header>

        <dl className="mt-5 grid gap-4 sm:grid-cols-3">
          <Item label="Inspection ID" value={inspection.id} mono />
          <Item label="Product" value={inspection.productName} />
          <Item label="Batch / lot" value={inspection.batch ?? "—"} />
          <Item
            label="Inspected on"
            value={new Date(inspection.createdAt).toLocaleString("en-IN")}
          />
          <Item label="Officer" value={inspection.officer} />
          <Item
            label="GPS Coordinates"
            value={
              inspection.location
                ? `${inspection.location.latitude}°, ${inspection.location.longitude}° (±${inspection.location.accuracy}m)`
                : "Not recorded"
            }
            mono
          />
        </dl>

        <section className="mt-6 flex flex-wrap items-center gap-4 rounded-md border border-border bg-surface p-4">
          <div>
            <p className="label-caps">Preliminary assessment</p>
            <p className="text-3xl font-semibold tabular-nums">
              {inspection.score}
              <span className="text-base text-muted-foreground"> / 100</span>
            </p>
          </div>
          <VerdictPill verdict={inspection.verdict} />
          <p className="text-xs text-muted-foreground sm:ml-auto sm:max-w-xs">
            AI-assisted preliminary assessment. Not a legal determination; subject to officer
            verification and physical measurement.
          </p>
        </section>

        {inspection.images.length > 0 && (
          <section className="mt-6">
            <p className="label-caps">Photographic evidence</p>
            <div className="mt-2 grid grid-cols-2 gap-3 sm:grid-cols-3">
              {inspection.images.map((src, i) => (
                <img
                  key={i}
                  src={src}
                  alt={`Evidence photograph ${i + 1}`}
                  className="rounded-md border border-border"
                />
              ))}
            </div>
          </section>
        )}

        <section className="mt-6">
          <p className="label-caps">Extracted declarations</p>
          <dl className="mt-2 grid gap-3 sm:grid-cols-2">
            <Item
              label="Manufacturer / packer"
              value={inspection.extracted.manufacturer ?? "Not detected"}
            />
            <Item label="Address" value={inspection.extracted.address ?? "Not detected"} />
            <Item label="Net quantity" value={inspection.extracted.netQuantity ?? "Not detected"} />
            <Item label="MRP" value={inspection.extracted.mrp ?? "Not detected"} />
            <Item
              label="Month & year of packing"
              value={inspection.extracted.mfgDate ?? "Not detected"}
            />
            <Item
              label="Consumer care"
              value={inspection.extracted.consumerCare ?? "Not detected"}
            />
          </dl>
        </section>

        <section className="mt-6">
          <p className="label-caps">Compliance checks &amp; officer decisions</p>
          <div className="mt-2 overflow-x-auto">
            <table className="w-full min-w-[640px] text-xs">
              <thead className="bg-surface text-left">
                <tr>
                  <th className="px-3 py-2">Requirement</th>
                  <th className="px-3 py-2">Rule</th>
                  <th className="px-3 py-2">Extracted</th>
                  <th className="px-3 py-2">Status</th>
                  <th className="px-3 py-2">Officer</th>
                </tr>
              </thead>
              <tbody>
                {inspection.checks.map((c) => (
                  <tr key={c.id} className="border-t border-border align-top">
                    <td className="px-3 py-2 font-medium">{c.requirement}</td>
                    <td className="px-3 py-2 text-muted-foreground">{c.ruleReference}</td>
                    <td className="px-3 py-2">{c.extractedValue ?? "Not detected"}</td>
                    <td className="px-3 py-2">
                      <StatusPill status={c.status} />
                    </td>
                    <td className="px-3 py-2 text-muted-foreground">
                      {c.decision.replace(/_/g, " ")}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </section>

        <section className="mt-6">
          <p className="label-caps">Violation summary</p>
          {violations.length === 0 ? (
            <p className="mt-2 text-sm text-muted-foreground">
              No mandatory declaration was found to be absent or non-standard in this assessment.
            </p>
          ) : (
            <ol className="mt-2 space-y-3">
              {violations.map((c, idx) => (
                <li
                  key={c.id}
                  className="rounded-md border border-destructive/25 bg-destructive/5 p-3"
                >
                  <p className="text-sm font-semibold">
                    {idx + 1}. {c.requirement} — {c.category}
                  </p>
                  <p className="mt-1 text-xs text-muted-foreground">{c.ruleReference}</p>
                  <p className="mt-1.5 text-sm">{c.explanation}</p>
                  <p className="mt-1.5 text-xs text-muted-foreground">
                    Evidence: {c.evidence} · Confidence {Math.round(c.confidence * 100)}% · Officer:{" "}
                    {c.decision.replace(/_/g, " ").toLowerCase()}
                  </p>
                </li>
              ))}
            </ol>
          )}
        </section>

        <footer className="mt-8 grid gap-6 border-t border-border pt-6 sm:grid-cols-2">
          <div>
            <p className="text-xs text-muted-foreground">Inspecting officer</p>
            <div className="mt-8 border-t border-border pt-1 text-sm">{inspection.officer}</div>
          </div>
          <div>
            <p className="text-xs text-muted-foreground">
              Countersigned (Controller, Legal Metrology)
            </p>
            <div className="mt-8 border-t border-border pt-1 text-sm text-muted-foreground">—</div>
          </div>
        </footer>
      </article>
    </AppShell>
  );
}

function Item({ label, value, mono }: { label: string; value: string; mono?: boolean }) {
  return (
    <div className="min-w-0">
      <dt className="text-[11px] font-semibold uppercase tracking-wide text-muted-foreground">
        {label}
      </dt>
      <dd className={`mt-0.5 text-sm break-words ${mono ? "font-mono" : ""}`}>{value}</dd>
    </div>
  );
}
