/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as InspectRouteImport } from './routes/inspect'
import { Route as InspectionsIndexRouteImport } from './routes/inspections.index'
import { Route as InspectionsIdRouteImport } from './routes/inspections.$id'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as ReportsIdRouteImport } from './routes/reports.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const InspectRoute = InspectRouteImport.update({
  id: '/inspect',
  path: '/inspect',
  getParentRoute: () => rootRouteImport,
} as any)
const InspectionsIndexRoute = InspectionsIndexRouteImport.update({
  id: '/inspections/',
  path: '/inspections/',
  getParentRoute: () => rootRouteImport,
} as any)
const InspectionsIdRoute = InspectionsIdRouteImport.update({
  id: '/inspections/$id',
  path: '/inspections/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIdRoute = ReportsIdRouteImport.update({
  id: '/reports/$id',
  path: '/reports/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/inspect': typeof InspectRoute
  '/inspections/$id': typeof InspectionsIdRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/reports/$id': typeof ReportsIdRoute
  '/inspections/': typeof InspectionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/inspect': typeof InspectRoute
  '/inspections/$id': typeof InspectionsIdRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/reports/$id': typeof ReportsIdRoute
  '/inspections': typeof InspectionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/inspect': typeof InspectRoute
  '/inspections/$id': typeof InspectionsIdRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/reports/$id': typeof ReportsIdRoute
  '/inspections/': typeof InspectionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/inspect'
    | '/inspections/$id'
    | '/products/$slug'
    | '/reports/$id'
    | '/inspections/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/inspect'
    | '/inspections/$id'
    | '/products/$slug'
    | '/reports/$id'
    | '/inspections'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/inspect'
    | '/inspections/$id'
    | '/products/$slug'
    | '/reports/$id'
    | '/inspections/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  InspectRoute: typeof InspectRoute
  InspectionsIdRoute: typeof InspectionsIdRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  ReportsIdRoute: typeof ReportsIdRoute
  InspectionsIndexRoute: typeof InspectionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspect': {
      id: '/inspect'
      path: '/inspect'
      fullPath: '/inspect'
      preLoaderRoute: typeof InspectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspections/': {
      id: '/inspections/'
      path: '/inspections'
      fullPath: '/inspections/'
      preLoaderRoute: typeof InspectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspections/$id': {
      id: '/inspections/$id'
      path: '/inspections/$id'
      fullPath: '/inspections/$id'
      preLoaderRoute: typeof InspectionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/$id': {
      id: '/reports/$id'
      path: '/reports/$id'
      fullPath: '/reports/$id'
      preLoaderRoute: typeof ReportsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  InspectRoute: InspectRoute,
  InspectionsIdRoute: InspectionsIdRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  ReportsIdRoute: ReportsIdRoute,
  InspectionsIndexRoute: InspectionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
